import { CssBaseline } from '@mui/material'
import Head from 'next/head'
import Layout from '../components/layout'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Red Umbrella | Waitlist</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
        />
        <meta name='apple-mobile-web-app-capable' content='yes' />
        <link rel='shortcut icon' href='/images/umbrella.svg' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/images/umbrella180.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/images/umbrella32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/images/umbrella16.png'
        />
      </Head>
      <CssBaseline />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
