import { CssBaseline } from '@mui/material'
import Head from 'next/head'
import Layout from '../components/layout'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Red Umbrella | Waitlist</title>
        <meta name='description' content='Generated by create next app' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name='apple-mobile-web-app-capable' content='yes' />
        <link rel='icon' href='/umbrella.svg' />
      </Head>
      <CssBaseline />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
